# .github/workflows/build-and-test.yml
on:
  workflow_dispatch:
    inputs:
      ACTIVE_API_URL:
        description: 'The URL of the scanner settings'
        default: 'https://ec2-44-202-50-212.compute-1.amazonaws.com/active'
        required: false
        type: string
      ACTIVE_SEVERITY_THRESHOLD:
        description: build disturb on error level supported values [high , medium, low, info, none]
        default: none
        required: false
        type: choice
        options:
          - high
          - medium
          - low
          - info
          - none
      ACTIVE_TEST_SUITE_ID:
        description: The Test suite id to be scanned.
        default: 94518edc-033c-4070-88f3-709c3d32b1f7
        required: true
        type: string
      ACTIVE_BASE_URL:
        description: Optional base url to override the the source base url for this scan.
        type: string
        required: false
        default: ''

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: Install Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm test
      - name: Daemonize our Node API service
        run: npm run start &

      - name: docker login
        uses: docker/login-action@v1
        with:
          registry: jfrog.cicd.nonamesec.com/noname-docker-release
          username: nns-devops@nonamesecurity.com
          password: ${{ secrets.ACTIVE_REGISTRY_PASSWORD }}

      - name: security test
        run: |
          docker run \
          --pull always \
          jfrog.cicd.nonamesec.com/noname-docker-release/active-cli:$(curl -k ${{github.event.inputs.ACTIVE_API_URL}}/backend/version) \
          scan \
          --api-url=${{ github.event.inputs.ACTIVE_API_URL }} \
          --api-token=${{ secrets.ACTIVE_API_TOKEN }} \
          --test-suite-id=${{ github.event.inputs.ACTIVE_TEST_SUITE_ID }} \
          --severity-threshold=${{ github.event.inputs.ACTIVE_SEVERITY_THRESHOLD }} \
          --base-url=${{ github.event.inputs.ACTIVE_BASE_URL }}

  deploy:
    needs: scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm test
      - name: Daemonize our Node API service
        run: npm run start &

      
